services:
  mongo-db:
    image: postgres:16-alpine3.20
    container_name: postgres-persistencio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persistencio
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql_16/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge