"""mirgation final mesmo

Revision ID: 19bc2b608ae6
Revises: 8e56e22a4453
Create Date: 2025-01-23 00:36:43.725673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bc2b608ae6'
down_revision: Union[str, None] = '8e56e22a4453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('funcionarios_projeto_id_fkey', 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'projeto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('funcionarios_projeto_id_fkey', 'funcionarios', 'projetos', ['projeto_id'], ['id'])
    # ### end Alembic commands ###
