"""adicionando relacoes

Revision ID: 299bbe588537
Revises: d08b8236ef51
Create Date: 2025-01-22 22:45:50.606987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299bbe588537'
down_revision: Union[str, None] = 'd08b8236ef51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'projetos', ['projeto_id'], ['id'])
    op.add_column('contratos', sa.Column('projeto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contratos', 'projetos', ['projeto_id'], ['id'])
    op.add_column('departamentos', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.alter_column('departamentos', 'orcamento',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('departamentos_gerente_id_fkey', 'departamentos', type_='foreignkey')
    op.create_foreign_key(None, 'departamentos', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('departamentos', 'gerente_id')
    op.add_column('funcionarios', sa.Column('departamento_id', sa.Integer(), nullable=False))
    op.add_column('funcionarios', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funcionarios', 'projetos', ['projeto_id'], ['id'])
    op.create_foreign_key(None, 'funcionarios', 'departamentos', ['departamento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'projeto_id')
    op.drop_column('funcionarios', 'departamento_id')
    op.add_column('departamentos', sa.Column('gerente_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departamentos', type_='foreignkey')
    op.create_foreign_key('departamentos_gerente_id_fkey', 'departamentos', 'funcionarios', ['gerente_id'], ['id'])
    op.alter_column('departamentos', 'orcamento',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('departamentos', 'empresa_id')
    op.drop_constraint(None, 'contratos', type_='foreignkey')
    op.drop_column('contratos', 'projeto_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'projeto_id')
    # ### end Alembic commands ###
