"""adicionando cliente.id à projeto

Revision ID: 43b83e10c69e
Revises: 299bbe588537
Create Date: 2025-01-22 23:39:00.200166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b83e10c69e'
down_revision: Union[str, None] = '299bbe588537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clientes_projeto_id_fkey', 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'projeto_id')
    op.alter_column('departamentos', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', 'SUSPENSO', name='statusenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('projetos', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projetos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'cliente_id')
    op.alter_column('departamentos', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ATIVO', 'INATIVO', 'SUSPENSO', name='statusenum'),
               existing_nullable=False)
    op.add_column('clientes', sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clientes_projeto_id_fkey', 'clientes', 'projetos', ['projeto_id'], ['id'])
    # ### end Alembic commands ###
