"""models principais do sistema (Sem relacionamentos)

Revision ID: 6d603f3aec6a
Revises: d6539c3153d9
Create Date: 2025-01-18 20:18:15.123780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d603f3aec6a'
down_revision: Union[str, None] = 'd6539c3153d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('cnpj_cpf', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('email_de_contato', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_cpf')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('condicoes_de_servico', sa.String(), nullable=False),
    sa.Column('vigecia', sa.Enum('ATIVO', 'INATIVO', 'SUSPENSO', name='statusenum'), nullable=False),
    sa.Column('qtd_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('gerente', sa.String(), nullable=False),
    sa.Column('orcamento', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'SUSPENSO', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('CNPJ', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('email_de_contato', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
