"""mirgation fiunal

Revision ID: ace7bccbcbbc
Revises: f9a183c689c9
Create Date: 2025-01-22 23:56:35.040244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace7bccbcbbc'
down_revision: Union[str, None] = 'f9a183c689c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
