"""reorganizando entidade de departamento

Revision ID: d08b8236ef51
Revises: 967eb8a0a620
Create Date: 2025-01-19 19:43:39.849916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08b8236ef51'
down_revision: Union[str, None] = '967eb8a0a620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamentos', sa.Column('gerente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departamentos', 'funcionarios', ['gerente_id'], ['id'])
    op.drop_column('departamentos', 'gerente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamentos', sa.Column('gerente', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'departamentos', type_='foreignkey')
    op.drop_column('departamentos', 'gerente_id')
    # ### end Alembic commands ###
