"""mirgation final 4

Revision ID: e416289ed7fa
Revises: ac6211572668
Create Date: 2025-01-23 00:04:48.796460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e416289ed7fa'
down_revision: Union[str, None] = 'ac6211572668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'projeto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'projeto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
