"""adicionando cliente.id à projeto

Revision ID: f9a183c689c9
Revises: 43b83e10c69e
Create Date: 2025-01-22 23:54:25.275275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a183c689c9'
down_revision: Union[str, None] = '43b83e10c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'projetos', ['projeto_id'], ['id'])
    op.drop_constraint('projetos_cliente_id_fkey', 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'cliente_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('projetos_cliente_id_fkey', 'projetos', 'clientes', ['cliente_id'], ['id'])
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'projeto_id')
    # ### end Alembic commands ###
